exclude = [
	"numpy/__config__.py",
	"numpy/distutils",
	"numpy/typing/_char_codes.py",
	"numpy/typing/tests/data",
	"spin/cmds.py",
	"vendored-meson" ]
[lint]
extend-select = [ "E" ]
ignore = [ "F", "E241", "E251", "E265", "E266", "E302", "E402", "E712", "E721", "E731", "E741", "W291", "W293", "W391" ]
